spring:
  task:
    scheduling:
      pool:
        size: 4
  application:
    name: MeterService
  datasource:
    url: jdbc:postgresql://electricity-billing-db.cxcg228yy6a8.ap-south-1.rds.amazonaws.com:5432/ebm_db
    username: postgres
    password: pvsEbmDb24$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com:
      wissen:
        meter:
          Meter: DEBUG
